### ISSUE TITLE
pacote `dpm` não encontrado

### ISSUE THREAD

**Issue by hslinhares** [splor-mg/aux-agrupamento-dcmefo#1]
@fjuniorr no contexto de https://github.com/splor-mg/atividades/issues/115 fiz a instalação do `requirements.txt` que inclui o pacote `dpm`

```
git+https://github.com/splor-mg/dpm.git@main
```

porém durante a execução do `Make file` surge a mensagem:

```
from dpm.utils import as_identifier
ModuleNotFoundError: No module named 'dpm'

```

O erro acontece em `transform.py` na linha:

```
from dpm.utils import as_identifier
```

Alguma sugestão?

**Comment by fjuniorr** [comment]
Eu não consegui reproduzir o seu erro. Você instalou as dependências com `python -m pip install -r requirements.txt` no lugar de `pip install -r requirements.txt`? As vezes isso gera esse tipo de erro.

Localmente no commit https://github.com/splor-mg/aux-agrupamento-dcmefo/commit/544207c1be9f1e212fad9ca76bd8d70c5b1378e8 depois de criar um ambiente virtual e instalar as dependências com:

```
python -m venv venv
source venv/bin/activate
python -m pip install -r requirements.txt
```

Ao tentar rodar o `make extract` eu recebo:

```
make extract
Traceback (most recent call last):
  File "/Users/fjunior/Projects/splor/dados-aux-agrupamento-dcmefo/main.py", line 25, in <module>
    app.command(name="extract")(extract_resource)
                                ^^^^^^^^^^^^^^^^
NameError: name 'extract_resource' is not defined
Rscript scripts/extract.R
Please make sure you have the right to access data from this Data Package for your intended use.
Follow applicable norms or requirements to credit the dataset and its authors.
Loading Microsoft Graph login for default tenant
```

O meu erro está acontecendo porque você não excluiu a linha:

https://github.com/splor-mg/aux-agrupamento-dcmefo/blob/544207c1be9f1e212fad9ca76bd8d70c5b1378e8/main.py#L25

**Comment by hslinhares** [comment]
@fjuniorr eu criei novamente a pasta `venv`, e utilizei o `requirements.txt` conforme o `cookiecutter` e o problema foi solucionado.

Outra questão agora que surgiu foi #2
