### ISSUE TITLE
Adicionar agendamento diário

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/aux-agrupamento-dcmefo#4]
Isso estava pendente de https://github.com/splor-mg/cookiecutter-datapackage/pull/42 mas agora já podemos realizar o agendamento.

**Comment by hslinhares** [comment]
@fjuniorr preciso que insira os `secrets` do docker

![image](https://github.com/splor-mg/aux-agrupamento-dcmefo/assets/43452663/ec9c8f10-1fb1-4830-be94-c17d201db0bc)

**Comment by fjuniorr** [comment]
Feito

**Comment by hslinhares** [comment]
Para funcionar corretamente no actions tique que comentar no makefile a linha `#include .env`
